# \#---------------------------------------------------------------------
# debug option
#---------------------------------------------------------------------

show_debug_info: true


#---------------------------------------------------------------------
# overall parameters
#---------------------------------------------------------------------

# control period [s]
ctrl_period: 0.04

# length span for resampling trajectory [m]
#   currentlly, resample uses linear interpolation, thus small sampling distance
#   causes sharp (not smoothing) path.
traj_resample_dist: 0.1


# path smoothing flug, must true except debugging
enable_path_smoothing: true

# recalculate yaw angle after resampling
enable_yaw_recalculation: true

# path smoothing low pass filler, moving average number
path_filter_moving_ave_num: 35

# Number of times tof applying path smoothing filter
path_smoothing_times: 1

# curvature calculation smoothing, larger makes smoother
#   curvature is calculated from three points: p(i-num), p(i), p(i+num)
curvature_smoothing_num: 35

# low pass filter for steering output command [Hz]
steering_lpf_cutoff_hz: 2.0

# stop mpc calculation when error is larger than the following value
admisible_position_error: 5.0 #[m]
admisible_yaw_error_deg: 45.0 #[deg]



#---------------------------------------------------------------------
# MPC algorithm parameters
#---------------------------------------------------------------------

# optimization solver type. option is "unconstraint_fast", "unconstraint", and "qpoases_hotstart"
qp_solver_type: "unconstraint_fast"

# vehicle model type for mpc prediction. option is "kinematics", "kinematics_no_delay"
vehicle_model_type: "kinematics"

# total prediction step
mpc_n: 70

# prediction period for one step [s] (predict holizon period = npc_n * mpc_dt)
mpc_dt: 0.1

# # weight parameters
# mpc_weight_lat_error: 0.1      # for Q[0,0]
# mpc_weight_heading_error: 0.1  # for Q[1,1]
# mpc_weight_heading_error_squared_vel_coeff: 0.0
# mpc_weight_steering_input: -5.0 # for R[0,0]
# mpc_weight_steering_input_vel_coeff: 2.5 # for R[0,0] = a + b * v
# mpc_weight_steering_input_squared_vel_coeff: 0.0
# mpc_weight_lat_jerk: 0.

# weight parameters
mpc_weight_lat_error: 0.1                         # for Q lateral error
mpc_weight_heading_error: 0.                      # for Q heading error
mpc_weight_heading_error_squared_vel_coeff: 0.3   # for Q heading error * vel
mpc_weight_steering_input: 1.0                    # for R referencve input error
mpc_weight_steering_input_squared_vel_coeff: 0.25 # for R referencve input error * vel
mpc_weight_lat_jerk: 0.0                          # to reduce lateral jerk
mpc_weight_endpoint_Q_scale: 5.0                  # endpoint error weight to improve mpc stability

# To reduce path noise, feedforward angle is set to zero when it is smaller than this value.
mpc_zero_ff_steer_deg: 2.0

#---------------------------------------------------------------------
# vehicle model parameters
#---------------------------------------------------------------------

# steering dynamics time constant (1d approzimation) [s]
vehicle_model_steer_tau: 0.40 # lexus: 0.2 + LPF delay

# wheel base length [m]
vehicle_model_wheelbase: 2.79 # lexus: 2.79

# steering angle limit [deg]
steer_lim_deg: 40.0

mass_fl: 600
mass_fr: 600
mass_rl: 600
mass_rr: 600
cf: 155494.663
cr: 155494.663
