#---------------------------------------------------------------------
# debug option
#---------------------------------------------------------------------

show_debug_info: true


#---------------------------------------------------------------------
# overall parameters
#---------------------------------------------------------------------

# control period [s]
ctrl_period: 0.04

# length span for resampling trajectory [m]
#   currentlly, resample uses linear interpolation, thus small sampling distance
#   causes sharp (not smoothing) path.
traj_resample_dist: 0.1


# path smoothing flug, must true except debugging
enable_path_smoothing: true

# recalculate yaw angle after resampling
enable_yaw_recalculation: true

# path smoothing low pass filler, moving average number
path_filter_moving_ave_num: 35

# Number of times tof applying path smoothing filter
path_smoothing_times: 1

# curvature calculation smoothing, larger makes smoother
#   curvature is calculated from three points: p(i-num), p(i), p(i+num)
curvature_smoothing_num: 35

# low pass filter for steering output command [Hz]
steering_lpf_cutoff_hz: 2.0

# stop mpc calculation when error is larger than the following value
admisible_position_error: 5.0 #[m]
admisible_yaw_error_deg: 45.0 #[deg]

# steering angle limit [deg]
steer_lim_deg: 40.0

#---------------------------------------------------------------------
# MPC algorithm parameters
#---------------------------------------------------------------------

# total prediction step
mpc_n: 70

# prediction period for one step [s] (predict holizon period = npc_n * mpc_dt)
mpc_dt: 0.1

# # weight parameters
# mpc_weight_lat_error: 0.1      # for Q[0,0]
# mpc_weight_heading_error: 0.1  # for Q[1,1]
# mpc_weight_heading_error_squared_vel_coeff: 0.0
# mpc_weight_steering_input: -5.0 # for R[0,0]
# mpc_weight_steering_input_vel_coeff: 2.5 # for R[0,0] = a + b * v
# mpc_weight_steering_input_squared_vel_coeff: 0.0
# mpc_weight_lat_jerk: 0.

# weight parameters
mpc_weight_lat_error: 0.1      # for Q[0,0]
mpc_weight_heading_error: 0.  # for Q[1,1]
mpc_weight_heading_error_squared_vel_coeff: 0.3
mpc_weight_steering_input: 1.0 # for R[0,0]
mpc_weight_steering_input_squared_vel_coeff: 0.25
mpc_weight_lat_jerk: 0.0

# time delay compensation
mpc_delay_compensation_time: 0.0 #[s]

# To reduce path noise effect, reference curvature is set to zeto when it is smaller than this valuse
mpc_zero_curvature_range: 0.01

#---------------------------------------------------------------------
# vehicle model parameters
#---------------------------------------------------------------------

# steering dynamics time constant (1d approzimation) [s]
vehicle_model_steer_tau: 0.040 # lexus: 0.2 + LPF delay

# wheel base length [m]
vehicle_model_wheelbase: 2.79 # lexus: 2.79
